class VerticalSpread:
	def __init__(self, spread_data_df):
		self.K1_Ask = spread_data_df["K1_Ask"]
		self.K1_Bid = spread_data_df["K1_Bid"]
		self.K1_Description = spread_data_df["K1_Description"]        
		self.K1_Exchange = spread_data_df["K1_Exchange"]        
		self.K1_Last_Sale = spread_data_df["K1_Last Sale"]        
		self.K1_Net = spread_data_df["K1_Net"]        
		self.K1_Open_Int = spread_data_df["K1_Open Int"]        
		self.K1_Strike = spread_data_df["K1_Strike"]        
		self.K1_Vol = spread_data_df["K1_Vol"]
		self.K1_Sigma = spread_data_df["K1_Sigma"]                
		self.K1_Delta = spread_data_df["K1_Delta"]                
		self.K1_Gamma = spread_data_df["K1_Gamma"]                
		self.K1_Theta = spread_data_df["K1_Theta"]                
		self.K1_Vega = spread_data_df["K1_Vega"]                
		self.K1_Entry = spread_data_df["K1_Entry"]

		self.K2_Ask = spread_data_df["K2_Ask"]
		self.K2_Bid = spread_data_df["K2_Bid"]
		self.K2_Description = spread_data_df["K2_Description"]        
		self.K2_Exchange = spread_data_df["K2_Exchange"]        
		self.K2_Last_Sale = spread_data_df["K2_Last Sale"]        
		self.K2_Net = spread_data_df["K2_Net"]        
		self.K2_Open_Int = spread_data_df["K2_Open Int"]        
		self.K2_Strike = spread_data_df["K2_Strike"]        
		self.K2_Vol = spread_data_df["K2_Vol"]
		self.K2_Sigma = spread_data_df["K2_Sigma"]                
		self.K2_Delta = spread_data_df["K2_Delta"]                
		self.K2_Gamma = spread_data_df["K2_Gamma"]                
		self.K2_Theta = spread_data_df["K2_Theta"]                
		self.K2_Vega = spread_data_df["K2_Vega"]                
		self.K2_Entry = spread_data_df["K2_Entry"]

		self.max_profit = spread_data_df["Max Profit"]
		self.max_risk = spread_data_df["Max Risk"]
		self.break_even = spread_data_df["Break Even"]
		self.delta = spread_data_df["Delta"]
		self.gamma = spread_data_df["Gamma"]
		self.theta = spread_data_df["Theta"]
		self.vega = spread_data_df["Vega"]